### ISSUE TITLE
Format of accepted Key File

### ISSUE THREAD

**Issue by 3turtle333** [kyrus/crypto-un-locker#1]
Hello,

This looks like a great script. 

I have all the available formats of the key file
Registry export
Your Private Key.bin
Private Key in plain text from the decryption service which is like:
-----BEGIN PRIVATE KEY-----

---

-----END PRIVATE KEY-----

I have been able to successfully use my .bin file using this method http://twist3d.net/cryptolocker/ so my key file is good.

So what format does the key file need to be in? I always get Unsuccessful loading key file: Could not parse a private key from file

Thanks

**Comment by jgarman** [comment]
You should be able to use the Your Private key.bin and the decryption
service plain text file (with the PRIVATE KEY markers). I've used both
successfully. Can you send me a copy of your private key to take a look
if you're still having trouble?
- jason

3turtle333 wrote:

**Comment by 3turtle333** [comment]
Thank you so much for your reply. I completely missed it.

Anyways, I used the official decrypter tool. It is actually very good, it
neatly writes out all the successes and failures. I was originally
interests in determining the list of encrypted files, this is why I wanted
to try your tool,  In the end i just went for the decryption. Too much time
was wasted.

Thanks again

**Comment by timdufrane** [comment]
Just so other people see, and might come to the same solution, the keys provided by the FireEye site have "BEGIN/END RSA PRIVATE KEY" in the output. The Python file is looking for "BEGIN/END PRIVATE KEY." Take out the RSA portion, and it should work fine.

To the author: thank you for this tool. You just saved me loads of time.

**Comment by jgarman** [comment]
Thanks for your feedback! I've changed the code to be more forgiving and it should now accept either "BEGIN RSA PRIVATE KEY" or "BEGIN PRIVATE KEY".

**Comment by timdufrane** [comment]
Awesome, thanks for your responsiveness, and thanks again for this great tool!

Edit: actually one more thing, in the output gained from FireEye's key search, there is no newline between the begin, key, and end portions. Omitting \n in the regex and stripping whitespace/newlines would likely be sufficient.

**Comment by jgarman** [comment]
Ah, you're right... I don't know why they didn't just bundle the key with the decryption tool when you download it. I'll take a look and see.

**Comment by timdufrane** [comment]
I believe that using this would be fine:
matches = ''.join(matches.split())
Should remove all whitespace, newlines, etc. from the input.
