### ISSUE TITLE
Help me to Encrypt

### ISSUE THREAD

**Issue by chandrabhushana** [kyrus/crypto-un-locker#3]
Hi ..
I successfully installed your script. M on the way to encrypt one folder and i give the command like this

 python CryptoUnLocker.py --keydir ~/workspace/encryption/testen/

Is this correct format ? .. But i got error like this 

(env)ri@ri-desktop:~/workspace/encryption/crypto-un-locker$ python CryptoUnLocker.py --keydir ~/workspace/encryption/testen/
usage: CryptoUnLocker.py [-h](--keyfile KEYFILE | --keydir KEYDIR | --detect)
                         [-r] [-v] [--dry-run] [-o DESTDIR] [--csv CSVFILE]
                         encrypted_filenames [encrypted_filenames ...]
CryptoUnLocker.py: error: too few arguments
# 

Help me to solve ...!

**Comment by chandrabhushana** [comment]
hi...
 I successfully installed your script , then run that script i am getting below error.

usage: CryptoUnLocker.py [-h](--keyfile KEYFILE | --keydir KEYDIR | --detect)
                         [-r] [-v] [--dry-run] [-o DESTDIR] [--csv CSVFILE]
                         encrypted_filenames [encrypted_filenames ...]
CryptoUnLocker.py: error: unrecognized arguments: /home/ri/workspace/encryption/testen/
(env)ri@ri-desktop:~/workspace/encryption/crypto-un-locker$ python CryptoUnLocker.py --keydir ~/workspace/encryption/testen/ -v ~/workspace/encryption/output -r ~/workspace/encryption/testen/

Help me to solve

**Comment by chandrabhushana** [comment]
when i am runing the CryptoUnLocker.py 

i am getting below error

usage: CryptoUnLocker.py [-h](--keyfile KEYFILE | --keydir KEYDIR | --detect)
                         [-r] [-v] [--dry-run] [-o DESTDIR] [--csv CSVFILE]
                         encrypted_filenames [encrypted_filenames ...]
CryptoUnLocker.py: error: unrecognized arguments: /home/ri/workspace/encryption/testen/

Help me to solve

**Comment by chandrabhushana** [comment]
hi...
I successfully installed your script , then run that script i am getting below error.

[-] Unsuccessful loading key file: Could not parse a private key from file: /home/ri/workspace/encryption/testen/id-rsa.ppk
[-] Unsuccessful loading key file: Could not parse a private key from file: /home/ri/workspace/encryption/testen/testemptydoc.txt~
[-] Unsuccessful loading key file: unpack_from requires a buffer of at least 8 bytes: /home/ri/workspace/encryption/testen/sample.txt~
[-] No key files were successfully loaded. Exiting.

Help me to solve

**Comment by jgarman** [comment]
This tool is for decrypting files encrypted by CryptoLocker. From the file names you've pasted in, you have a PuTTY private key file, which is not compatible with this tool. For more information, see http://www.bleepingcomputer.com/virus-removal/cryptolocker-ransomware-information.
